# Dependencies
markdown:         redcarpet


# Permalinks
permalink:        pretty

# Setup
title:            Vincent Chu
description:      'U of T  -   Class of 2022'
baseurl:          /

author:
  name:           'Vincent Chu'
  url:            https://github.com/Vincentcchu


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Vincentcchu
