# Dependencies
markdown:         redcarpet


# Permalinks
permalink:        pretty

# Setup
title:            Vincent Chu
description:      'Data Scientist - Accelex'
baseurl:          /

author:
  name:           'Vincent Chu'
  url:            https://github.com/Vincentcchu


# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Vincentcchu
